# Generated by Django 5.0.4 on 2024-05-14 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geo_db", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="image",
            field=models.ImageField(upload_to="media/"),
        ),
    ]
